theme: jekyll-theme-cayman
title: ReaSCAN
name: ReaSCAN: The Reasoning-based SCAN Benchmark
description: ReaSCAN: The Reasoning-based SCAN Benchmark
show_downloads: true
is_project_page: true
github:
  zip_url: https://drive.google.com/file/d/1tRCl-ciPSz-XRDYFgy0O36YpDl48VydP/view?usp=sharing
  tar_url: https://drive.google.com/file/d/1tRCl-ciPSz-XRDYFgy0O36YpDl48VydP/view?usp=sharing
  repository_url: https://github.com/frankaging/Reason-SCAN
