title: "ReaSCAN: Compositional Reasoning in Language Grounding"
description: Zhengxuan Wu, Elisa Kreiss, Desmond C. Ong, Christopher Potts
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman